### ISSUE TITLE
Re-allocating Accommodation Reps

### ISSUE THREAD

**Issue by rachelinnes** [xsd08tfu/sw-bug-tracker#234] opened 2019-12-02 11:08 UTC
## Describe the bug ##
I know this is already being worked on, but just a note to say the system is still automatically re-allocating accommodation reps. Thanks :)

**Comment by xsd08tfu** [comment] 2019-12-03 22:05
Duplicate of #233

**Closed by xsd08tfu** 2019-12-03 22:05 UTC
